server:
  port: 8090
  
spring:
  application:
    name: BuildJava-App
  data:
    mongodb:
      database: onlineshopping
      host: localhost
      port: 27017
      uri: mongodb://localhost/onlineshopping
      collections: inventory
      repositories:
        enable: true

    
#logging:
#  config: classpath:log4j2.xml
