server:
  port: 8090
  
spring:
  application:
    name: BuildJava-App
  data:
    mongodb:
      database: onlineshopping
      host: localhost
      port: 27017
      uri: mongodb://localhost/onlineshopping
      repositories:
        enable: true

#eureka:
#  client:
#    serviceUrl: http://localhost:8761/eureka
#
